# 需要检查的文件
files:
  include: 'src/**/*.s+(a|c)ss'

rules:
  # 缩进
  indentation:
    - 2
    -
      size: 2
  # 类名格式
  class-name-format:
    - allow-leading-underscore: false
    - convention: hyphenatedlowercase
