language: node_js

node_js:
  - "6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm config set spin false
  - npm install -g npm@3
  - npm install -g webpack
  - npm install

script:
  - npm run build
